version: '3'

services:
  db:
    image: mysql:latest
    environment:
        MYSQL_DATABASE: 'godb'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: '1234'
        MYSQL_ROOT_PASSWORD: '1234'
    ports:
        - '3306:3306'
    volumes:
        - type: bind
          source: data
          target: /var/lib/mysql

